### ISSUE TITLE
Photron cameras control

### ISSUE THREAD

**Issue by susnicek** [djorlando24/pySciCam#1]
Dear pySciCam developer,
first of all I would like to thank you for the code you are sharing with others.
From the code description one think is unclear for me:
The code provides only the image formats conversion or it is also able to download the images directly from camera using hw. communication e.g. via GigE, USB?
I am currently looking for a Linux open-source sw. able to control Photron cameras. Any advice for this problem?

Looking forward to your answer!
Best regards, Susnicek

**Comment by djorlando24** [comment]
This library handles format conversions, not direct link with the camera. For that, you need the Photron FastCam Viewer software which can be downloaded free from Photron.

**Comment by susnicek** [comment]
Thank you for the reply and for the advice. Unfortunately, the software from Photron is not for Linux...

**Comment by djorlando24** [comment]
correct, unfortunately you need Windows. My solution for GigE cameras is to run a Virtualbox VM with PFV in it. it’s a bit slower than running Windows on the bare metal but it’ll let you try PFV without buying a Windows license until you’re sure you need it. For a free Windows trial VM image for app development you can go here;
https://developer.microsoft.com/en-us/windows/downloads/virtual-machines

**Comment by susnicek** [comment]
Thank you for the good idea!
