### ISSUE TITLE
Trying to import large mraw files (larger than uint32), leads to error "Python int too large to convert to C long" 

### ISSUE THREAD

**Issue by shnubs** [djorlando24/pySciCam#3]
This issue is located in the photron_mraw.pyx in line 58.
cdef long nbytes = os.path.getsize(filename)

**Comment by shnubs** [comment]
I ran

`import os

path = r'E:\[...]\large.mraw'

print(os.path.getsize(path))`

and it returns the right filesize (8579973120) without a problem. So it seems to be a problem with the type definition of long. I tried long long instead. No luck.

**Comment by shnubs** [comment]
Actually changing some type definitions of variables in the photron_mraw.pyx file and then recompiling/re-running the setup did do the trick. My first intuition to simply switch the type definition to long long was right.

**Comment by djorlando24** [comment]
Thanks, I wasn't able to reproduce the error on my x86_64 machine even with 10GB+ files, so this is a compiler and architecture specific issue with type defs. Feel free to do pull request to change those type definitions.
